== Introduction

This discussion paper is concerned with the topic of quantum computing (QC) and its applicability to addressing geospatial problems. The Open Geospatial Consortium (OGC) is an innovative, member led organization concerned with creation and maintenance of standards for geospatial data, processing, and adjacent technologies. It has been operating for over 20 years with a guiding principle that geospatial assets should be FAIR (Findable, Accessible, Interoperable, Reusable). Quantum computing is of interest to the OGC because of its applicability to uniquely complex, geospatial problems. 

The focus of the experimentation described in later sections was _integration_ and _experimentation_ rather than discerning new quantum algorithms or looking at generation after next capabilities. Part of the motivation was the pace of technological change and specifically the rise of technologies such as ChatGPT and LLMs in general which came to public prominence almost overnight and answering the following questions:

* What if QC has it's _ChatGPT moment?_ 
* What could QC be used for in the geospatial domain?  
* What, if any, are the advantages of using QC in the geospatial domain either now or in the future?
* What is the integration path for QC with existing geospatial technologies? 

Although quantum technologies are not new, the recent interest QC for computationally difficult applications is notable with many large technology companies spinning up quantum divisions in both the applications and engineering specialisms. Additionally, there are specialist companies working on engineering QCs, with further private entities working on applications. This paper provides a discussion on applications and potential applications for quantum computing, although there is an introduction to some of the concepts and challenges with QC it is largely focused on the practical applications of QC for geospatial problems but does provide a cursory discussion of the approaches to QC and the challenges with the engineering and hardware. As with many technologies, QC is constantly evolving in terms of capabilities, speed and overall hardware.

The promise of QC has been understood prior to any hardware implementations. Perhaps the most well-known (and for some, concerning) applications is the ability for QCs to factor very large numbers. Although this may seem a trivial application for these machines, many encryption protocols are built upon the principle that deriving prime factors from a very large number is computationally hard, although not impossible. A salient example is the use of public and private keys for securing pieces of information where both the public and private key are required to decrypt information and read the contents. Public key are transmitted with the understanding that they maybe intercepted, but because of the nature of computing factors from large numbers using classical computing, it is computationally hard to derive the private key with knowledge of the public key. However, generating the public key from the private key is computationally trivial. Although current QCs are not able to crack this type of encryption with current, small to medium sized machines, encrypted information can be collected with the ambition of decrypting it in the near future. Interestingly, the ability for QC to factor large numbers was proven in the 1990s by Peter Shor (Shor's algorithm) long before practical implementations of QCs.

Another often cited QC application is search of large databases. This application was investigated by Grover who produced an algorithm. As with Shor's algorithm, a quantum advantage to searching a database was shown albeit quadratic rather than exponential. An additional consideration for practical implementation is the reliance on an _oracle function_, which somehow derives what the result of the search should be and the QC locates the record or records in the database. 

There are several other applications that are gaining traction for QC use cases including interaction with sensors and _quantum machine learning_. At time of writing, the ML applications do not have the same level of _proof_ as the previous examples, but have shown promise.

== Quantum Computing

Classical computers work using _bits_. Bits are the fundamental building blocks of computation that can have one of two states at any one time (usually styled as 0 and 1 or _off_ and _on_). QC is different in that its building blocks are _qubits_, which exist in a superposition of 0 and 1. Often this is visualized as _Bloch Sphere_ where a spin upwards is analogous to _0_ and a spin downwards is _1_. Any other spin is a superposition of 0 and 1 because it contains components of both. This ability to hold a superposition of qubits is fundamental to QC approaches.

A second component of QC is _entanglement_, which was famously dismissed by Einstein as "spooky action at a distance." Entanglement happens when two particles are linked and can effect each other's state regardless of their distance from each other. This also has implications for quantum teleportation and information exchange, although this does not cause issues with causality because information regarding the state change on one particle is required to get information out of the second particle and the transmission of the information must be done classically with all of the speed of light restrictions associated with it.

An additional consideration of QC (of which there are many) is that the process is non-deterministic, unlike classical computing that will produce the same result every time provided the initial conditions are identical, QC can produce different results with the same input. A method of addressing this issue it to perform the calculation many times (1000s) and averaging the results in some way (usually the mode if talking energy states).

=== Types of quantum computing

QC implementations have emerged from large technology companies as well as small and middle size disruptive businesses looking to leverage practical QC as the technology evolves. Unlike _classical computing_ which is generalized, QC is specialized to solve certain types of problems. Although QC shows promise for some applications, it is not currently envisaged that QC or Quantum Processing Units (QPUs) will replace classical computers, this is not like the invention of the microchip replacing the valve approach to generalized computation! Currently there are two conceptual approaches to QC, these are:

* Circuit based.
* Adiabatic or annealers.

Circuit based QC are potentially closer to generalized classical computing. These are the machines that can factor large numbers and perform search algorithms as described in the introduction. Indicatively, this type of QC is where much of the focus of the research community lies, this maybe because it has the potential to offer quantum advantage, that is, it can solve problems that cannot be solved in a sensible time by a classical computation approach (note that this includes the world's most powerful supercomputers).

Adiabatic quantum computing (AQC) is a different type of computation that is setup specifically for solving optimization problems. The hardware and topology of AQC is completely different from circuit based approaches, which means that unlike generalized classical computing, you cannot run circuit based algorithms on AQCs as they way that they perform computation is fundamentally different. Simplistically, whilst circuit based QC is concerned with the manipulation and transformation of individual qubits, ADQ looks to put the entire system in a very low energy state and then transfer the problem space slowly into the AQC with the result to the entire problem emerging from maintenance of the low energy state. One way to think about this is the machine state starts off representing a horizontal plane, that is, it is flat. After the problem has been transferred into the ADQ, the plane is no longer flat, instead it has a topology, much like a hilly landscape. The optimal solution of the problem space is the deepest valley such that if a ball was dropped onto this hypothetical landscape, the _ball_ would end up at the lowest point in the landscape which represents the solution. Computationally, this means that the machine needs to _find the ball_ to get the solution.

There are many online resources that provide a fuller explanation including the physics of QC and quantum information theory, but it is beyond the scope of this discussion paper that is focused on applications. 

=== Quantum hardware and engineering challenges

The hardware and engineering challenges with QC have contributed to its relatively slow progress compared to other technologies such as artificial intelligence, or the increase in power of graphical processing units (GPUs). Two big challenges with QC hardware are _noise_ and _decoherence_. Qubits are fragile and cannot hold state for long periods of time. There is also the fundamental problem of interacting with a system that for all intents and purposes needs to be isolated from the outside work to maintain coherence. One method of addresses these issues is to increase the number of physical qubits to create a smaller number of _logical_ qubits where the outputs from each bank of physical qubits is corrected. The result of this approach is that it makes quantum computation far more reliable that those without the correction, however, it requires many times more physical qubits to produce a number of logical qubits that can do computation of practical and useful size.

From a hardware perspective, there are different approaches to creating physical machines and addressing the challenges of noise and decoherence. Some examples are:

. Superconducting approaches - where materials are cooled to close to absolute zero to produce quantum effects.
. Trapped ions - ions trapped using electromagnetic fields.
. Photons - using particles of light to perform computation.
. Neutral atoms - use of lasers to arrange atoms into grids.
. Annealers - use of phenomenon _quantum tunnelling_ to find the minima of a function for optimization problems (the main concern of this paper with respect to geospatial applications).

There are other methods being actively investigated, however, the number of approaches demonstrates that experimentation is still being conducted, and the _best_ technology has yet to be settled on. This is in contrast to classical computing where silicon and to a lesser extent copper are the metals used to create microchips. 

Overall, these technologies represent engineering challenges. Unlike CPUs which reside locally inside classical computers, it appears unlikely that a QPU will sit along side CPUs like GPUs do, albeit in the cloud considering the size of current quantum computers (square metres in size). The current generation of QCs are of a similar size to the early classical mainframes and therefore require infrastructure to host locally. The main method of accessing quantum computation today is to use cloud connected services.

=== Interaction with quantum computers

Creating and executing jobs for todays quantum computers is done through software development kits (SDKs). As QPU time can be expensive, the SDKs often offer a _quantum simulator_ to test code locally with the quantum output simulated via a classical computer. Some SDKs, especially for circuit based machines offer the ability to create and simulate quantum circuits. Individual qubits are tasked within the circuit to produce a result; although this is useable for the size of QCs that are available now, it will quickly become impractical with even a small number of qubits. Many of these SDKs offer the ability to call a QC with parameters to execute a known computation without having to do low-level programming, a salient example of this is with quantum annealing where the problem space is restricted to optimization problems. Some examples of SDKs are as follows:

. Qiskit - IBM - used for constructing and executing circuits.
. Cirq - Google - Python library tailored to Google's quantum machines.
. Ocean Software - used for quantum annealing on D-Wave's machines.
. Microsoft Quantum Development Kit - uses Q#, a language for expressing quantum algorithms.

There are also many more SDKs with some intending to be cross platform.

Much of the work described in this paper was conducted using the Ocean Software SDK to execute D-Wave cloud connected quantum computers.



