.Preface

The OGC has been defining standards in a spatial context for over 20 years. As new technologies emerge and become relevant to solving spatial problems, the need for standards to integrate these new technologies into existing enterprises is crucial. This, coupled with ensuring data and services are FAIR (Findable, Accessible, Interoperable, Reusable) provides a roadmap for rapid technological integration. Prior to standardization, it is prudent to understand the applicability of new technologies to OGC concerns, which in this context is geospatial optimization problems. This document describes the emerging technology of quantum computing through a short background and history followed by the practical implementation of three use cases. Future work will start to look at the case for a formal interface, data model, or best practice for using quantum computing in a geospatial enterprise for solving optimization problems.

Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. The Open Geospatial Consortium shall not be held responsible for identifying any or all such patent rights.

Recipients of this document are requested to submit, with their comments, notification of any relevant patent claims or other intellectual property rights of which they may be aware that might be infringed by any implementation of the standard set forth in this document, and to provide supporting documentation.

[abstract]
== Abstract

This discussion paper provides an overview of the emerging technology of quantum computing with a focus on its applicability to solving geospatial problems. The advantages of using a computer built upon the properties of quantum mechanics to some complex (_NP-hard_) problems has been known since the mid-1990s. However, the engineering challenges with building quantum computers have meant that quantum computers of sufficient size to solve practical problems have only recently become available. Although there are many applications that may benefit from using a quantum computing approach, this paper focuses on _optimization_ problems as there are many within the geospatial domain, however, optimization problems are best solved by _adiabatic quantum computing_ which is a specialized machine that is setup to only solve optimization problems. Three use cases are discussed and run on a cloud connected D-Wave quantum computer; the traveling salesperson problem, structural imbalance in a social network, and optimization of satellite constellations according to a cost/benefit balance. The findings are that practical quantum computing for geospatial analytics is practical, useful, and through the use of hybrid samplers can provide real-world advantages over classical computing. 

